const articlesData = [
    // --- LEVEL A1 (3-4 Kalimat Dasar) ---
    { 
        level: "a1", title: "1. Mein Morgen", 
        german: ["Ich heiße Anna.", "Jeden Tag stehe ich um sechs Uhr auf.", "Ich trinke eine Tasse Kaffee und esse ein Brot."], 
        indo: ["Nama saya Anna.", "Setiap hari saya bangun jam enam.", "Saya minum secangkir kopi dan makan sepotong roti."] 
    },
    { 
        level: "a1", title: "2. Das Haustier", 
        german: ["Das ist ein Hund.", "Er heißt Felix.", "Er ist klein und braun.", "Er spielt gerne im Garten und mag Fleisch."], 
        indo: ["Ini adalah seekor anjing.", "Namanya Felix.", "Dia kecil dan berwarna cokelat.", "Dia suka bermain di taman dan menyukai daging."] 
    },
    { 
        level: "a1", title: "3. Im Supermarkt", 
        german: ["Heute gehe ich einkaufen.", "Ich brauche Milch, Äpfel und Tomaten.", "Der Supermarkt ist nicht weit von hier.", "Ich bezahle an der Kasse."], 
        indo: ["Hari ini saya pergi berbelanja.", "Saya butuh susu, apel, dan tomat.", "Supermarket itu tidak jauh dari sini.", "Saya membayar di kasir."] 
    },
    { 
        level: "a1", title: "4. Das Wetter", 
        german: ["Das Wetter ist heute sehr schön.", "Die Sonne scheint am blauen Himmel.", "Es ist sehr warm und angenehm.", "Wir gehen heute im Park spazieren."], 
        indo: ["Cuaca hari ini sangat bagus.", "Matahari bersinar di langit biru.", "Sangat hangat dan menyenangkan.", "Kami pergi berjalan-jalan di taman hari ini."] 
    },

    // --- LEVEL A2 (4-5 Kalimat, Ada Konjungsi) ---
    { 
        level: "a2", title: "1. Ein Ausflug nach Berlin", 
        german: ["Letztes Wochenende bin ich nach Berlin gereist.", "Die Stadt ist sehr groß und historisch interessant.", "Am Samstag habe ich das Brandenburger Tor besucht.", "Später habe ich traditionelle Currywurst probiert.", "Der Ausflug hat mir großen Spaß gemacht."], 
        indo: ["Akhir pekan lalu saya pergi ke Berlin.", "Kota ini sangat besar dan menarik secara sejarah.", "Pada hari Sabtu saya mengunjungi Gerbang Brandenburg.", "Kemudian saya mencoba sosis kari tradisional.", "Tamasya itu sangat menyenangkan bagi saya."] 
    },
    { 
        level: "a2", title: "2. Meine Wohnung", 
        german: ["Ich wohne in einer kleinen Wohnung im Zentrum der Stadt.", "Sie hat zwei Zimmer, eine Küche und ein helles Badezimmer.", "Im Wohnzimmer steht ein gemütliches Sofa.", "An der Wand hängt ein großes Poster von den Bergen.", "Die Aussicht aus dem Fenster ist wirklich wunderbar."], 
        indo: ["Saya tinggal di sebuah apartemen kecil di pusat kota.", "Tempat ini memiliki dua kamar, sebuah dapur, dan kamar mandi yang terang.", "Di ruang tamu ada sofa yang nyaman.", "Di dinding tergantung poster besar pegunungan.", "Pemandangan dari jendela benar-benar luar biasa."] 
    },
    { 
        level: "a2", title: "3. Das Hobby", 
        german: ["In meiner Freizeit fahre ich oft mit dem Fahrrad in den Park.", "Dort treffe ich mich mit meinen Freunden zum Picknick.", "Wenn das Wetter schlecht ist, bleibe ich lieber zu Hause.", "Dann lese ich spannende Kriminalromane auf dem Sofa.", "Manchmal höre ich dabei auch ruhige Musik."], 
        indo: ["Di waktu luang, saya sering mengendarai sepeda ke taman.", "Di sana saya bertemu dengan teman-teman untuk piknik.", "Jika cuaca buruk, saya lebih suka tinggal di rumah.", "Lalu saya membaca novel kriminal yang menegangkan di sofa.", "Terkadang saya juga mendengarkan musik tenang sambil membacanya."] 
    },
    { 
        level: "a2", title: "4. Kochen macht Spaß", 
        german: ["Am Sonntag koche ich immer für meine Familie.", "Wir bereiten zusammen italienische Nudeln mit einer frischen Tomatensoße zu.", "Das Kochen dauert etwa eine Stunde.", "Nach dem Essen trinken wir gemeinsam Tee.", "Wir sprechen über unsere Pläne für die nächste Woche."], 
        indo: ["Pada hari Minggu saya selalu memasak untuk keluarga saya.", "Kami menyiapkan pasta Italia bersama dengan saus tomat segar.", "Memasaknya memakan waktu sekitar satu jam.", "Setelah makan kami minum teh bersama.", "Kami membicarakan rencana kami untuk minggu depan."] 
    },

    // --- LEVEL B1 (5-6 Kalimat, Topik Sosial & Opini) ---
    { 
        level: "b1", title: "1. Die Bedeutung des Sports", 
        german: ["Regelmäßige körperliche Bewegung spielt eine entscheidende Rolle für unsere Gesundheit.", "Viele Menschen klagen heutzutage über chronischen Stress im Beruf.", "Sportliche Aktivitäten bieten hierbei einen hervorragenden Ausgleich.", "Ob man joggt, schwimmt oder ins Fitnessstudio geht, ist zweitrangig.", "Wichtig ist vor allem die Kontinuität und der Spaß an der Bewegung.", "Darüber hinaus fördert Sport den Teamgeist, wenn man im Verein spielt."], 
        indo: ["Olahraga fisik teratur memainkan peran krusial bagi kesehatan kita.", "Banyak orang mengeluhkan stres kronis dalam pekerjaan saat ini.", "Aktivitas olahraga menawarkan penyeimbang yang sangat baik dalam hal ini.", "Apakah seseorang berlari, berenang, atau pergi ke gym adalah hal sekunder.", "Yang terpenting adalah konsistensi dan kesenangan dalam bergerak.", "Selain itu, olahraga mendorong semangat tim jika bermain dalam klub."] 
    },
    { 
        level: "b1", title: "2. Wohnungssuche", 
        german: ["Die Suche nach einer bezahlbaren Wohnung in einer Großstadt stellt junge Berufstätige vor enorme Herausforderungen.", "Die Mieten steigen kontinuierlich, während das Angebot an kleinen Apartments stark begrenzt ist.", "Viele Bewerber müssen monatelang suchen, bis sie eine passende Unterkunft finden.", "Aus diesem Grund entscheiden sich immer mehr Menschen dazu, in Wohngemeinschaften zusammenzuleben.", "Dadurch lassen sich nicht nur die monatlichen Fixkosten deutlich reduzieren.", "Man findet so auch schneller Anschluss in einer neuen, fremden Stadt."], 
        indo: ["Pencarian tempat tinggal yang terjangkau di kota besar menghadirkan tantangan besar bagi para pekerja muda.", "Harga sewa terus meningkat, sementara ketersediaan apartemen kecil sangat terbatas.", "Banyak pelamar harus mencari selama berbulan-bulan sampai mereka menemukan akomodasi yang cocok.", "Karena alasan ini, semakin banyak orang memutuskan untuk tinggal bersama di apartemen berbagi.", "Dengan ini, tidak hanya biaya tetap bulanan yang dapat ditekan secara signifikan.", "Seseorang juga dapat bergaul lebih cepat di kota baru yang asing."] 
    },
    { 
        level: "b1", title: "3. Reisen und Horizont", 
        german: ["Das Reisen in fremde Länder ermöglicht es uns, den eigenen Horizont auf faszinierende Weise zu erweitern.", "Man lernt völlig neue Kulturen, kulinarische Traditionen sowie alternative Lebensweisen kennen.", "Oft ist die Vorbereitung und die Organisation der Reise etwas anstrengend.", "Trotz dieser organisatorischen Hürden lohnt sich die Mühe fast immer.", "Man kehrt meistens mit unvergesslichen Erinnerungen in den normalen Alltag zurück.", "Diese wertvollen Lebenserfahrungen prägen unsere Persönlichkeit nachhaltig."], 
        indo: ["Bepergian ke negeri asing memungkinkan kita memperluas wawasan dengan cara yang menakjubkan.", "Seseorang dapat mengenal budaya yang sepenuhnya baru, tradisi kuliner, serta cara hidup alternatif.", "Seringkali persiapan dan pengorganisasian perjalanan agak melelahkan.", "Meskipun ada hambatan organisasional ini, usahanya hampir selalu sepadan.", "Seseorang biasanya kembali ke rutinitas normal dengan kenangan tak terlupakan.", "Pengalaman hidup yang berharga ini membentuk kepribadian kita secara berkelanjutan."] 
    },
    { 
        level: "b1", title: "4. Digitale Medien", 
        german: ["Digitale Medien und Smartphones sind aus unserem modernen Alltag absolut nicht mehr wegzudenken.", "Sie erleichtern zwar die Kommunikation über große Distanzen immens.", "Außerdem bieten sie einen extrem schnellen Zugang zu weltweiten Informationen.", "Allerdings bergen diese Technologien auch ernsthafte Gefahren für die Gesundheit.", "Insbesondere die ständige Erreichbarkeit kann zu einer tiefen digitalen Erschöpfung führen.", "Aus diesem Grund werden bewusste Offline-Pausen für viele Menschen immer wichtiger."], 
        indo: ["Media digital dan ponsel pintar kini sudah menjadi bagian tak terpisahkan dari keseharian modern kita.", "Memang, mereka sangat memudahkan komunikasi melintasi jarak yang jauh.", "Selain itu, mereka menawarkan akses yang sangat cepat ke informasi global.", "Namun, teknologi ini juga menyimpan bahaya serius bagi kesehatan.", "Khususnya ketersediaan yang konstan dapat mengarah pada kelelahan digital yang mendalam.", "Karena alasan ini, jeda luring (offline) yang sadar menjadi semakin penting bagi banyak orang."] 
    },

    // --- LEVEL B2 (6-7 Kalimat, Kosakata Profesional & Analitis) ---
    { 
        level: "b2", title: "1. Der Wandel der Arbeitswelt", 
        german: ["Die fortschreitende Digitalisierung und Globalisierung revolutionieren unsere traditionelle Arbeitsumgebung grundlegend.", "Das klassische, starre Büromodell weicht zunehmend flexibleren Strukturen wie dem Homeoffice und der ortsunabhängigen Remote-Arbeit.", "Einerseits gewinnen Arbeitnehmer dadurch eine deutlich verbesserte und individuellere Work-Life-Balance.", "Andererseits verschwimmen die Grenzen zwischen Berufs- und Privatleben zusehends, was ein hohes Maß an Selbstdisziplin erfordert.", "Arbeitgeber stehen nun vor der Herausforderung, digitale Infrastrukturen sicher und effizient bereitzustellen.", "Zudem muss der soziale Zusammenhalt im Team auch über virtuelle Kommunikationswege aufrechterhalten werden.", "Lebenslanges Lernen ist somit nicht länger eine Option, sondern eine absolute berufliche Notwendigkeit geworden."], 
        indo: ["Digitalisasi dan globalisasi yang terus berlanjut secara mendasar merevolusi lingkungan kerja tradisional kita.", "Model kantor klasik yang kaku semakin bergeser menuju struktur yang lebih fleksibel seperti bekerja dari rumah dan kerja jarak jauh lintas lokasi.", "Di satu sisi para pekerja mendapatkan keseimbangan hidup yang jauh lebih baik dan individual.", "Di sisi lain batasan antara kehidupan profesional dan pribadi semakin kabur, yang menuntut tingkat disiplin diri yang tinggi.", "Para pemberi kerja kini dihadapkan pada tantangan untuk menyediakan infrastruktur digital secara aman dan efisien.", "Selain itu, kohesi sosial dalam tim juga harus dipertahankan melalui jalur komunikasi virtual.", "Oleh karena itu, pembelajaran seumur hidup tidak lagi sekadar pilihan, melainkan keharusan profesional yang mutlak."] 
    },
    { 
        level: "b2", title: "2. Energiewende", 
        german: ["Der rasche Übergang zu erneuerbaren Energien ist zweifellos das zentrale ökologische Projekt unserer Zeit.", "Um den fatalen globalen Temperaturanstieg wirksam zu bremsen, müssen Industrie und Gesellschaft massiv umdenken.", "Es erfordert enorme Investitionen in nachhaltige Technologien wie Windkraft, Geothermie und Photovoltaik.", "Dennoch stoßen diese notwendigen Maßnahmen lokal häufig auf bürokratische Hürden und gesellschaftliche Skepsis.", "Viele Bürger befürchten eine Beeinträchtigung des Landschaftsbildes oder sorgen sich um die langfristige Versorgungssicherheit.", "Daher ist ein transparenter Dialog zwischen Politik, Wirtschaft und der Bevölkerung unabdingbar.", "Nur durch gemeinsame Kompromisse lässt sich der drohende Klimakollaps noch rechtzeitig abwenden."], 
        indo: ["Transisi cepat menuju energi terbarukan tanpa diragukan lagi merupakan proyek ekologis sentral di masa kini.", "Untuk mengerem kenaikan suhu global yang fatal secara efektif, industri dan masyarakat harus mengubah cara berpikir secara masif.", "Hal ini membutuhkan investasi besar-besaran pada teknologi berkelanjutan seperti tenaga angin, panas bumi, dan fotovoltaik.", "Meskipun demikian, langkah-langkah yang diperlukan ini secara lokal seringkali menemui hambatan birokrasi dan skeptisisme sosial.", "Banyak warga khawatir akan kerusakan lanskap atau cemas mengenai keamanan pasokan jangka panjang.", "Oleh karena itu, dialog yang transparan antara politik, ekonomi, dan penduduk sangatlah mutlak.", "Hanya melalui kompromi bersama, ancaman keruntuhan iklim dapat dicegah tepat pada waktunya."] 
    },
    { 
        level: "b2", title: "3. Mehrsprachigkeit", 
        german: ["In einer stark vernetzten Weltwirtschaft wird die sicher beherrschte Mehrsprachigkeit zu einem entscheidenden Wettbewerbsvorteil.", "Unternehmen agieren heute zunehmend auf internationalen Märkten und suchen gezielt nach polyglotten Fachkräften.", "Dabei wird nicht nur eine hervorragende fachliche Qualifikation vorausgesetzt, sondern vor allem auch interkulturelle Sensibilität.", "Wer die Sprache seiner Geschäftspartner spricht, baut schneller Vertrauen auf und vermeidet kostspielige Missverständnisse.", "Daher investieren moderne Bildungssysteme verstärkt in den frühzeitigen und immersiven Fremdsprachenunterricht an Schulen.", "Auch im Erwachsenenalter erfreuen sich Sprachreisen und digitale Lernplattformen einer stetig wachsenden Beliebtheit.", "Letztlich ist jede neu erlernte Sprache ein Schlüssel zu einer anderen, faszinierenden Welt."], 
        indo: ["Dalam ekonomi global yang sangat saling terhubung, penguasaan multibahasa yang fasih menjadi keunggulan kompetitif yang menentukan.", "Perusahaan saat ini semakin banyak beroperasi di pasar internasional dan secara khusus mencari tenaga ahli poliglot.", "Dalam hal ini, tidak hanya kualifikasi teknis yang sangat baik yang diutamakan, tetapi terutama juga kepekaan lintas budaya.", "Siapa pun yang berbicara bahasa mitra bisnisnya akan membangun kepercayaan lebih cepat dan menghindari kesalahpahaman yang mahal.", "Oleh karena itu, sistem pendidikan modern semakin berinvestasi pada pembelajaran bahasa asing yang dini dan imersif di sekolah-sekolah.", "Bahkan di usia dewasa, wisata bahasa dan platform pembelajaran digital menikmati popularitas yang terus berkembang.", "Pada akhirnya, setiap bahasa baru yang dipelajari adalah kunci menuju dunia lain yang menakjubkan."] 
    },
    { 
        level: "b2", title: "4. Medienkompetenz", 
        german: ["Die nahezu unkontrollierte Verbreitung von Desinformationen in sozialen Netzwerken stellt unsere demokratischen Institutionen vor ernsthafte Probleme.", "Algorithmen bevorzugen oft polarisierende Inhalte, da diese eine höhere Interaktionsrate bei den Nutzern generieren.", "Um dieser gefährlichen Entwicklung wirksam entgegenzuwirken, ist die gezielte Förderung von Medienkompetenz unerlässlich.", "Bürger müssen lernen, digitale Quellen kritisch zu hinterfragen und Informationen anhand verifizierter Fakten zu überprüfen.", "Es reicht nicht mehr aus, Nachrichten passiv zu konsumieren; eine aktive Quellenkritik ist gefordert.", "Auch die Plattformbetreiber stehen in der ethischen Verantwortung, Mechanismen gegen systematische Manipulationen zu implementieren.", "Eine wehrhafte Demokratie benötigt informierte und reflektierte Bürger im digitalen Raum."], 
        indo: ["Penyebaran disinformasi yang hampir tidak terkontrol di jaringan sosial menghadirkan masalah serius bagi institusi demokratis kita.", "Algoritma seringkali mengutamakan konten yang mempolarisasi, karena konten tersebut menghasilkan tingkat interaksi yang lebih tinggi dari pengguna.", "Untuk melawan perkembangan berbahaya ini secara efektif, peningkatan literasi media secara terarah sangatlah esensial.", "Warga negara harus belajar mempertanyakan sumber digital secara kritis dan memverifikasi informasi berdasarkan fakta yang terbukti.", "Tidak cukup lagi hanya mengonsumsi berita secara pasif; kritik sumber yang aktif sangat dituntut.", "Para pengelola platform juga memikul tanggung jawab etis untuk mengimplementasikan mekanisme guna melawan manipulasi sistematis.", "Demokrasi yang tangguh membutuhkan warga negara yang terinformasi dan reflektif di ruang digital."] 
    },

    // --- LEVEL C1 (7-8 Kalimat, Sangat Akademik, Diskursus Publik) ---
    { 
        level: "c1", title: "1. Künstliche Intelligenz", 
        german: ["Die exponentielle Weiterentwicklung und Implementierung künstlicher Intelligenz in gesellschaftliche Kernbereiche evoziert fundamentale ethische Fragestellungen.", "Während Befürworter auf die beispiellose Effizienzsteigerung in der medizinischen Diagnostik und der industriellen Fertigung verweisen, formiert sich zunehmend kritischer Widerstand.", "Skeptiker warnen nachdrücklich vor irreversiblen sozialen Ungleichheiten und der schleichenden Entmachtung des menschlichen Subjekts durch undurchsichtige, proprietäre Algorithmen.", "Ein wesentliches Problemfeld stellt die sogenannte 'Black-Box-Problematik' dar, bei der die Entscheidungsfindung neuronaler Netze selbst für Experten kaum noch nachvollziehbar ist.", "Folglich bedarf es eines stringenten regulatorischen Rahmens, der technologische Innovation nicht abwürgt, aber ethische Mindeststandards verbindlich durchsetzt.", "Ein interdisziplinärer Diskurs zwischen Informatikern, Philosophen und Juristen ist unabdingbar, um die algorithmische Bias-Bildung zu minimieren.", "Letztendlich muss gewährleistet bleiben, dass die Technologie dem Wohl der gesamten Menschheit dient und nicht lediglich elitäre Machtmonopole zementiert."], 
        indo: ["Pengembangan eksponensial dan implementasi kecerdasan buatan ke dalam sektor-sektor inti masyarakat memicu pertanyaan etis yang fundamental.", "Sementara para pendukung merujuk pada peningkatan efisiensi yang belum pernah terjadi sebelumnya dalam diagnostik medis dan manufaktur industri, resistensi kritis semakin terbentuk.", "Para skeptis memperingatkan dengan tegas tentang ketimpangan sosial yang tidak dapat diubah dan penggusuran kekuasaan subjek manusia secara perlahan oleh algoritma eksklusif yang buram.", "Salah satu area masalah utama adalah 'problematika kotak hitam', di mana pengambilan keputusan jaringan saraf tiruan hampir tidak dapat dipahami lagi bahkan oleh para ahli.", "Akibatnya, diperlukan kerangka peraturan yang ketat, yang tidak mencekik inovasi teknologi, tetapi menegakkan standar minimum etis secara mengikat.", "Sebuah diskursus interdisipliner antara ilmuwan komputer, filsuf, dan ahli hukum sangat mutlak untuk meminimalkan pembentukan bias algoritmik.", "Pada akhirnya, harus tetap dijamin bahwa teknologi mengabdi pada kesejahteraan seluruh umat manusia dan tidak semata-mata memperkuat monopoli kekuasaan elitis."] 
    },
{ 
        level: "c1", title: "2. Ökonomische Dynamiken", 
        german: ["Die strukturelle Integrität globaler Finanzmärkte korreliert in hohem Maße mit volatilen geopolitischen Stabilitätsfaktoren und komplexen makroökonomischen Indikatoren.", "Unvorhergesehene, asymmetrische Krisenherde können hochgradig vernetzte Supply Chains weltweit innerhalb kürzester Zeit paralysieren.", "Eine derartige Disruption führt unweigerlich zu Angebotsverknappungen, welche wiederum massive inflationäre Tendenzen in den Industriestaaten verstärken.", "Zentralbanken sind in diesem Spannungsfeld gefordert, durch präzise kalibrierte geldpolitische Steuerungsinstrumente flexibel und antizyklisch zu agieren.", "Die Gratwanderung zwischen der Eindämmung der Inflation durch Leitzinserhöhungen und der Vermeidung einer tiefgreifenden Rezession erfordert außergewöhnliches analytisches Fingerspitzengefühl.", "Darüber hinaus zwingt die fortschreitende Deglobalisierung viele multinationale Konzerne dazu, ihre Produktionsstätten zu diversifizieren und teilweise zu reshoring-Strategien überzugehen.", "Diese Paradigmenwechsel deuten auf eine signifikante Transformation der neoliberalen Weltwirtschaftsordnung hin, deren finale Architektur noch ungewiss ist."], 
        indo: ["Integritas struktural pasar keuangan global berkorelasi tinggi dengan faktor stabilitas geopolitik yang volatil dan indikator makroekonomi yang kompleks.", "Titik krisis asimetris yang tidak terduga dapat melumpuhkan rantai pasok yang sangat terhubung secara global dalam waktu yang sangat singkat.", "Disrupsi semacam itu mau tidak mau mengarah pada kelangkaan pasokan, yang pada gilirannya memperkuat tren inflasi masif di negara-negara industri.", "Dalam medan ketegangan ini, bank sentral dituntut untuk bertindak fleksibel dan kontrasiklikal melalui instrumen pengaturan kebijakan moneter yang dikalibrasi secara presisi.", "Aksi menyeimbangkan (tali kawat) antara pembendungan inflasi melalui kenaikan suku bunga acuan dan penghindaran resesi yang mendalam menuntut kepekaan analitis yang luar biasa.", "Lebih jauh lagi, deglobalisasi yang terus berlanjut memaksa banyak perusahaan multinasional untuk mendiversifikasi fasilitas produksi mereka dan sebagian beralih ke strategi 'reshoring'.", "Perubahan paradigma ini menunjukkan transformasi signifikan dari tatanan ekonomi global neoliberal, yang arsitektur akhirnya masih belum pasti."] 
    },
    { 
        level: "c1", title: "3. Demografischer Wandel", 
        german: ["Der unaufhaltsam voranschreitende demografische Wandel konfrontiert die westlichen Wohlfahrtsstaaten mit historisch beispiellosen, strukturellen Belastungsproben.", "Die steigende Lebenserwartung gepaart mit sinkenden Geburtenraten führt zu einer bedenklichen Überalterung der Gesellschaft, welche die Solidarsysteme an ihre Belastungsgrenzen treibt.", "Besonders die nachhaltige Finanzierbarkeit der umlagefinanzierten Rentensysteme sowie der adäquate Ausbau der pflegerischen Infrastruktur stehen im Zentrum der politischen Debatte.", "Eine simple, lineare Erhöhung des gesetzlichen Renteneintrittsalters erweist sich dabei oft als sozialpolitisch brisant und makroökonomisch unzureichend.", "Flankierende, innovative Maßnahmen, wie etwa die Implementierung gesteuerter Zuwanderungskonzepte zur Akquise ausländischer Fachkräfte, sind absolut unerlässlich geworden.", "Gleichzeitig muss das inländische Arbeitskräftepotenzial durch gezielte Weiterbildungsprogramme und verbesserte Vereinbarkeit von Familie und Beruf vollends ausgeschöpft werden.", "Die Bewältigung dieser demografischen Disruption erfordert einen generationenübergreifenden Konsens, der Partikularinteressen dem langfristigen Gemeinwohl unterordnet."], 
        indo: ["Perubahan demografi yang maju tanpa henti menghadapkan negara-negara kesejahteraan barat pada ujian beban struktural yang belum pernah terjadi sebelumnya dalam sejarah.", "Peningkatan harapan hidup yang dibarengi dengan penurunan angka kelahiran mengarah pada penuaan masyarakat yang mengkhawatirkan, yang mendorong sistem solidaritas ke batas kapasitasnya.", "Secara khusus, pembiayaan berkelanjutan dari sistem pensiun berbasis pay-as-you-go serta perluasan infrastruktur perawatan yang memadai berada di pusat perdebatan politik.", "Peningkatan usia pensiun wajib secara linear dan sederhana dalam hal ini seringkali terbukti sensitif secara sosial-politik dan tidak mencukupi secara makroekonomi.", "Langkah-langkah inovatif pendamping, seperti implementasi konsep imigrasi yang terkontrol untuk akuisisi tenaga ahli asing, telah menjadi hal yang mutlak diperlukan.", "Pada saat yang sama, potensi tenaga kerja domestik harus dimanfaatkan sepenuhnya melalui program pendidikan lanjutan yang terarah dan peningkatan keseimbangan antara keluarga dan karier.", "Penanggulangan disrupsi demografis ini menuntut konsensus antargenerasi, yang menundukkan kepentingan golongan demi kesejahteraan umum jangka panjang."] 
    },
    { 
        level: "c1", title: "4. Wissenschaftliche Evidenz", 
        german: ["In einer von extrem hoher Komplexität und multiplen Krisen geprägten Epoche bildet wissenschaftliche Evidenz das unabdingbare Fundament für evidenzbasierte politische Entscheidungsprozesse.", "Die Objektivierbarkeit von Datenmengen ist essenziell, um ideologisch motivierte Narrative zu dekonstruieren und rationale, nachhaltige Strategien zu implementieren.", "Dennoch zeigt sich in der politischen Praxis erschreckend häufig eine gravierende Diskrepanz zwischen empirisch gesicherten Forschungsergebnissen und den populistischen Wahrnehmungsmustern in der Öffentlichkeit.", "Emotionale Framing-Strategien und kognitive Dissonanzen führen dazu, dass valide Fakten zugunsten bequemer, aber trügerischer Illusionen ignoriert werden.", "Dies erfordert eine fundamentale Neuausrichtung des wissenschaftlichen Wissenstransfers, der sich nicht länger auf den akademischen Elfenbeinturm beschränken darf.", "Wissenschaftler müssen proaktiv in den gesellschaftlichen Dialog treten, komplexe Zusammenhänge verständlich artikulieren und gleichzeitig die inhärenten Unsicherheiten wissenschaftlicher Erkenntnisgewinnung transparent kommunizieren.", "Nur eine resilient informierte Gesellschaft, die Ambiguitätstoleranz besitzt, kann den vielschichtigen Herausforderungen des 21. Jahrhunderts erfolgreich begegnen."], 
        indo: ["Dalam era yang dicirikan oleh kompleksitas yang sangat tinggi dan krisis ganda, bukti ilmiah membentuk fondasi yang tak terelakkan untuk proses pengambilan keputusan politik yang berbasis bukti.", "Objektivikasi kumpulan data sangatlah esensial untuk mendekonstruksi narasi yang bermotivasi ideologis dan mengimplementasikan strategi yang rasional dan berkelanjutan.", "Meskipun demikian, dalam praktik politik seringkali secara mengejutkan terlihat adanya diskrepansi yang parah antara hasil riset yang terjamin secara empiris dan pola persepsi populis di tengah publik.", "Strategi pembingkaian emosional dan disonansi kognitif menyebabkan fakta yang valid diabaikan demi ilusi yang nyaman namun menipu.", "Hal ini menuntut reorientasi fundamental dari transfer pengetahuan ilmiah, yang tidak boleh lagi membatasi diri pada menara gading akademik.", "Para ilmuwan harus secara proaktif memasuki dialog sosial, mengartikulasikan keterkaitan yang kompleks dengan cara yang mudah dipahami, sekaligus mengomunikasikan ketidakpastian yang melekat pada pemerolehan pengetahuan ilmiah secara transparan.", "Hanya masyarakat dengan informasi tangguh, yang memiliki toleransi ambiguitas, yang dapat berhasil menghadapi tantangan berlapis-lapis abad ke-21."] 
    },

    // --- LEVEL C2 (8+ Kalimat, Filosofis, Hermeneutik, Sastra Sangat Berat) ---
    { 
        level: "c2", title: "1. Dekonstruktion von Diskursen", 
        german: ["Die dekonstruktive Untersuchung hegemonialer Sprachstrukturen verlangt eine elaborierte, poststrukturalistische hermeneutische Methodologie.", "Deren primäres Ziel ist es, die tief in der Syntax verborgenen, impliziten Machtasymmetrien innerhalb kulturell tradierter Texte gnadenlos offenzulegen.", "Indem der Forscher die scheinbare, unhinterfragte Universalität historisch kontingenter Setzungen problematisiert, erodiert der ontologische Wahrheitsanspruch des herrschenden Narrativs.", "Diese Destabilisierung der Semantik eröffnet einen dringend benötigten epistemologischen Freiraum für die Konzeptualisierung alternativer, marginalisierter Subjektivitätskonzepte.", "Solche Diskurspraktiken bewegen sich radikal jenseits etablierter eurozentrischer Dogmatismen und starrer binärer Oppositionen.", "Vielmehr zwingt die Dekonstruktion den Rezipienten, die aporische Natur der Sprache als Vehikel der Bedeutungskonstitution selbst anzuerkennen.", "Jeder Text trägt demnach den Keim seiner eigenen Subversion in sich, da sich die Signifikanten einer fixierten Sinnzuschreibung permanent entziehen.", "Folglich ist das Lesen als ein unendlicher Prozess des Verfehlens und Neu-Einschreibens zu begreifen, der jede Form hermetischer Autorität konsequent unterläuft."], 
        indo: ["Investigasi dekonstruktif terhadap struktur bahasa hegemonik menuntut metodologi hermeneutik post-strukturalis yang rumit.", "Tujuan utamanya adalah untuk secara tanpa ampun menyingkapkan asimetri kekuasaan implisit yang tersembunyi jauh di dalam sintaksis di dalam teks-teks tradisi budaya.", "Dengan cara peneliti memproblematikan universalitas semu yang tak terbantahkan dari ketetapan yang secara historis bersifat kontingen, klaim kebenaran ontologis dari narasi penguasa menjadi terkikis.", "Destabilisasi semantik ini membuka ruang kebebasan epistemologis yang sangat dibutuhkan untuk konseptualisasi dari konsep subjektivitas alternatif yang terpinggirkan.", "Praktik-praktik diskursus semacam ini bergerak secara radikal jauh melampaui dogmatisme eurosentris yang mapan dan oposisi biner yang kaku.", "Sebaliknya, dekonstruksi memaksa penerima pesan untuk mengakui sifat aporik dari bahasa itu sendiri sebagai kendaraan pembentukan makna.", "Oleh karena itu, setiap teks membawa benih subversinya sendiri di dalam dirinya, karena sang penanda secara permanen menghindar dari pelekatan makna yang tetap.", "Akibatnya, membaca harus dipahami sebagai proses kegagalan dan penulisan ulang yang tak terbatas, yang secara konsisten merongrong segala bentuk otoritas hermetik."] 
    },
    { 
        level: "c2", title: "2. Epistemologische Axiome", 
        german: ["Die Fundierung moderner naturwissenschaftlicher Erkenntnistheorie basiert unweigerlich auf transzendentalen, a priori gesetzten Axiomen.", "Die absolute Gültigkeit dieser prämissenhaften Grundannahmen lässt sich jedoch empirisch niemals abschließend verifizieren, sondern lediglich im Sinne einer pragmatischen Notwendigkeit postulieren.", "Diese unauflösbare philosophische Antinomie verdeutlicht auf schmerzhafte Weise die inhärente Limitation der menschlichen Rationalität.", "Das epistemische Subjekt scheitert systematisch bei dem ambitionierten Versuch, die ontologische Gesamtstruktur des Kosmos vollumfänglich und ohne blinde Flecken zu durchdringen.", "Der radikale Konstruktivismus folgert daraus, dass jede wissenschaftliche Theorie nicht die Realität 'an sich' abbildet, sondern lediglich eine viabele Konstruktion des Beobachters darstellt.", "Somit wird der Positivismus des 19. Jahrhunderts als naive Illusion entlarvt, welche die instrumentelle Verfasstheit des Messapparates ausblendet.", "Erkenntnis ist demnach stets an die Kontingenz historisch gewachsener Paradigmen gebunden, wie Thomas Kuhn eindrücklich demonstrierte.", "Der absolute Geist, der die Welt in ihrer Totalität begreift, bleibt somit eine metaphysische Fiktion, an deren Stelle eine demütige, fehlbare Epistemologie der Näherungswerte treten muss."], 
        indo: ["Landasan epistemologi ilmu pengetahuan alam modern tak pelak lagi didasarkan pada aksioma-aksioma transendental yang ditetapkan secara a priori.", "Namun, validitas absolut dari asumsi dasar yang bersifat premis ini tidak akan pernah dapat diverifikasi secara empiris secara tuntas, melainkan hanya dapat dipostulatkan dalam kerangka kebutuhan pragmatis.", "Antinomi filosofis yang tak terpecahkan ini memperjelas dengan cara yang menyakitkan tentang batasan inheren dari rasionalitas manusia.", "Subjek epistemik secara sistematis gagal dalam upaya ambisius untuk menembus struktur ontologis keseluruhan kosmos secara paripurna dan tanpa titik buta.", "Konstruktivisme radikal menyimpulkan dari hal ini bahwa setiap teori ilmiah tidak menggambarkan realitas 'pada dirinya sendiri', melainkan sekadar merepresentasikan konstruksi yang viabel dari sang pengamat.", "Dengan demikian, positivisme abad ke-19 diekspos sebagai ilusi naif yang mengabaikan sifat instrumental dari aparatus pengukuran.", "Oleh karena itu, pengetahuan selalu terikat pada kontingensi paradigma yang tumbuh secara historis, sebagaimana didemonstrasikan dengan impresif oleh Thomas Kuhn.", "Roh absolut, yang memahami dunia dalam totalitasnya, dengan demikian tetap menjadi fiksi metafisik, yang posisinya harus digantikan oleh epistemologi nilai aproksimasi yang rendah hati dan bisa keliru."] 
    },
    { 
        level: "c2", title: "3. Phänomenologische Ästhetik", 
        german: ["Die phänomenologische Annäherung an ästhetische Artefakte entzieht sich per definitionem jeglicher objektivierenden, quantifizierbaren Reduktion.", "Sie rückt vielmehr das unverfälschte, primäre Sinnerlebnis und die transitorische, prä-reflexive Affizierung des Betrachters schonungslos ins Zentrum der ästhetischen Kontemplation.", "Kunst fungiert in diesem hochgradig subjektiven Prozess als ein resonanztheoretisches, liminales Medium.", "Sie artikuliert jene existenziellen Grunderfahrungen, die sich dem starren Begriffsapparat der diskursiven Vernunft systematisch entziehen.", "Indem das Kunstwerk die alltägliche Wahrnehmungsroutine durchbricht, bewirkt es eine Epoche – eine phänomenologische Einklammerung der gewohnten Weltsicht.", "In diesem auratischen Moment der ästhetischen Erfahrung offenbart sich die Welt nicht als bloßes Objekt der Manipulation, sondern als Bedeutungsraum purer Präsenz.", "Die Aufgabe der Hermeneutik besteht folglich nicht darin, eine eindeutige 'Botschaft' des Werkes zu decodieren, sondern den vielschichtigen Prozess des Verstehens selbst zu reflektieren.", "Dadurch wird der Horizont des Sagbaren und Fühlbaren signifikant erweitert, wodurch das Subjekt in einen heilsamen Zustand der Selbstentfremdung und Neufindung versetzt wird."], 
        indo: ["Pendekatan fenomenologis terhadap artefak estetika, menurut definisinya, menghindari segala bentuk reduksi yang mengobjektifikasi dan dapat dikuantifikasi.", "Sebaliknya, pendekatan ini secara blak-blakan menempatkan pengalaman makna primer yang tak tercampur dan afeksi pra-reflektif yang transitoris dari pengamat ke dalam pusat kontemplasi estetika.", "Seni dalam proses yang sangat subjektif ini berfungsi sebagai medium liminal teoretis-resonansi.", "Seni mengartikulasikan pengalaman-pengalaman dasar eksistensial yang secara sistematis menghindar dari aparatus konseptual kaku milik nalar diskursif.", "Dengan cara karya seni mendobrak rutinitas persepsi sehari-hari, ia memicu sebuah 'Epoche' – sebuah pengurungan fenomenologis dari pandangan dunia yang terbiasa.", "Dalam momen auratik dari pengalaman estetika ini, dunia mengungkapkan dirinya bukan sekadar sebagai objek manipulasi, melainkan sebagai ruang makna dari kehadiran murni.", "Tugas hermeneutik pada akibatnya bukanlah untuk mendekodekan sebuah 'pesan' yang gamblang dari karya tersebut, melainkan untuk merefleksikan proses berlapis-lapis dari pemahaman itu sendiri.", "Dengan demikian, cakrawala tentang apa yang dapat diungkapkan dan dirasakan diperluas secara signifikan, di mana subjek dipindahkan ke dalam kondisi yang menyembuhkan dari pengasingan diri dan penemuan diri baru."] 
    },
    { 
        level: "c2", title: "4. Dialektik der Rationalisierung", 
        german: ["In konsequenter Fortführung der Kritischen Theorie der Frankfurter Schule offenbart die Dialektik der technokratischen Rationalisierung eine zutiefst paradoxe Totalisierung der Gesellschaft.", "Jene instrumentelle Beherrschung der Natur, die im Zeitalter der Aufklärung einst triumphierend zur Emanzipation des autonomen Subjekts proklamiert wurde, schlägt nun dialektisch um.", "Sie manifestiert sich in einer subtilen, aber allumfassenden Form der Entfremdung, in welcher der Mensch zum bloßen, austauschbaren Funktionsglied eines autopoietischen, ökonomischen Verwertungszusammenhangs degradiert wird.", "Die sogenannte Kulturindustrie perfidioniert diesen Prozess, indem sie das Bewusstsein der Massen durch standardisierte Unterhaltungsprodukte sediert und reglementiert.", "Kritische Reflexion wird durch konformistischen Konsumzwang substituiert, wodurch der eindimensionale Mensch, wie ihn Marcuse skizzierte, zur traurigen soziologischen Realität avanciert.", "Selbst die Sprache wird ihrer poetischen und transzendenten Dimensionen beraubt und zur reinen, operativen Informationsübermittlung funktionalisiert.", "Ein Ausweg aus diesem stählernen Gehäuse der Hörigkeit erfordert einen radikalen Akt der Negation, der sich der assimilierenden Logik der kapitalistischen Verwertungsmaschinerie verweigert.", "Die utopische Hoffnung ruht somit einzig auf der bewussten Pflege des Nicht-Identischen, jenem Rest an Subjektivität, der sich der totalitären Erfassung durch den Systemimperativ noch widersetzt."], 
        indo: ["Sebagai kelanjutan yang konsisten dari Teori Kritis Mazhab Frankfurt, dialektika rasionalisasi teknokratis mengungkapkan totalisasi masyarakat yang sangat paradoks.", "Penguasaan instrumental atas alam tersebut, yang pada Zaman Pencerahan dahulu diproklamasikan secara penuh kemenangan untuk emansipasi subjek yang otonom, kini berbalik secara dialektis.", "Hal itu bermanifestasi dalam bentuk alienasi yang halus namun mencakup segala hal, di mana manusia terdegradasi menjadi sekadar roda fungsi yang dapat digantikan dari konteks pemanfaatan ekonomi yang bersifat autopoietik.", "Apa yang disebut sebagai industri budaya menyempurnakan proses ini secara curang, dengan cara membius dan meregulasi kesadaran massa melalui produk-produk hiburan yang distandardisasi.", "Refleksi kritis disubstitusi oleh paksaan konsumsi yang konformis, yang melaluinya manusia satu dimensi, sebagaimana digambarkan oleh Marcuse, naik menjadi realitas sosiologis yang menyedihkan.", "Bahkan bahasa dirampas dari dimensi puitis dan transendennya, serta difungsionalisasikan menjadi murni transmisi informasi yang operatif.", "Jalan keluar dari sangkar baja kepatuhan ini menuntut sebuah tindakan negasi yang radikal, yang menolak logika asimilasi dari mesin pemanfaatan kapitalis.", "Oleh karena itu, harapan utopis semata-mata bersandar pada pemeliharaan yang sadar atas yang Non-Identik, yaitu sisa-sisa subjektivitas yang masih melawan penangkapan totalitarian oleh imperatif sistem."] 
    }
];